# tasks file
---
- name: install dependencies
  ansible.builtin.apt:
    name: "{{ packer_io_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - packer-io
    - packer-io-dependencies

- name: create (download) directory
  ansible.builtin.file:
    path: "{{ packer_io_downloads_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags:
    - configuration
    - packer-io
    - packer-io-download

- name: download
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/packer/{{ packer_io_version }}/packer_{{ packer_io_version }}_linux_{{ packer_io_machine_map[ansible_machine] }}.zip"
    dest: "{{ packer_io_downloads_path }}/packer_{{ packer_io_version }}_linux_{{ packer_io_machine_map[ansible_machine] }}.zip"
    owner: root
    group: root
    mode: '0644'
  tags:
    - configuration
    - packer-io
    - packer-io-download

- name: create (install) directory
  ansible.builtin.file:
    path: "{{ packer_io_install_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags:
    - configuration
    - packer-io
    - packer-io-install

- name: install
  ansible.builtin.unarchive:
    src: "{{ packer_io_downloads_path }}/packer_{{ packer_io_version }}_linux_{{ packer_io_machine_map[ansible_machine] }}.zip"
    dest: "{{ packer_io_install_path }}"
    creates: "{{ packer_io_install_path }}/packer"
    copy: false
  tags:
    - configuration
    - packer-io
    - packer-io-install

- name: verify
  ansible.builtin.command: >
    {{ packer_io_install_path }}/packer --version
  register: _verify_version
  failed_when: "packer_io_version not in _verify_version.stdout"
  changed_when: false
  tags:
    - configuration
    - packer-io
    - packer-io-install
    - packer-io-install-verify
