# tasks file for packer-io
---
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
  with_items: packer_io_dependencies
  tags: [configuration, packer-io, packer-io-dependencies]

- name: create (download) directory
  file:
    path: "{{ packer_io_downloads_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: [configuration, packer-io, packer-io-download]

- name: download
  get_url:
    url: "https://dl.bintray.com/mitchellh/packer/packer_{{ packer_io_version }}_linux_{{ packer_io_machine_map[ansible_machine] }}.zip"
    dest: "{{ packer_io_downloads_path }}/packer_{{ packer_io_version }}_linux_{{ packer_io_machine_map[ansible_machine] }}.zip"
    owner: root
    group: root
    mode: 0644
  tags: [configuration, packer-io, packer-io-download]

- name: create (install) directory
  file:
    path: "{{ packer_io_install_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: [configuration, packer-io, packer-io-install]

- name: install
  unarchive:
    src: "{{ packer_io_downloads_path }}/packer_{{ packer_io_version }}_linux_{{ packer_io_machine_map[ansible_machine] }}.zip"
    dest: "{{ packer_io_install_path }}"
    creates: "{{ packer_io_install_path }}/packer"
    copy: false
  tags: [configuration, packer-io, packer-io-install]
